// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoG5zU8EzdPPFrXFstx0licFDklaxs83M',
    appId: '1:974459699084:web:8d47fa11d39ca31968a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    authDomain: 'elimisha-90787.firebaseapp.com',
    storageBucket: 'elimisha-90787.firebasestorage.app',
    measurementId: 'G-YBP1DZ3VC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_t14ixbvACi7Bk2wiEQ6lWOG7MFd61iI',
    appId: '1:974459699084:android:26d53a933598930a68a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    storageBucket: 'elimisha-90787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vaTsgPgH1Rdp5ms8ehbgVB0tNa379eE',
    appId: '1:974459699084:ios:057b53220829afbd68a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    storageBucket: 'elimisha-90787.firebasestorage.app',
    iosBundleId: 'com.elimisha.elimisha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vaTsgPgH1Rdp5ms8ehbgVB0tNa379eE',
    appId: '1:974459699084:ios:057b53220829afbd68a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    storageBucket: 'elimisha-90787.firebasestorage.app',
    iosBundleId: 'com.elimisha.elimisha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoG5zU8EzdPPFrXFstx0licFDklaxs83M',
    appId: '1:974459699084:web:58540bef6bd21d6768a0a9',
    messagingSenderId: '974459699084',
    projectId: 'elimisha-90787',
    authDomain: 'elimisha-90787.firebaseapp.com',
    storageBucket: 'elimisha-90787.firebasestorage.app',
    measurementId: 'G-LKZMLB63QT',
  );
}
